"""mudando default de finished

Revision ID: 0a792e7a140a
Revises: 76854ec0af54
Create Date: 2023-06-26 15:37:12.740579
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0a792e7a140a'
down_revision = '76854ec0af54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
