"""testing

Revision ID: 3bc654deaa8b
Revises: 86264a915ac6
Create Date: 2023-06-13 14:11:55.115306
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3bc654deaa8b'
down_revision = '86264a915ac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customers', sa.Column('new_field', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'new_field')
    # ### end Alembic commands ###
