"""add user model

Revision ID: 40a8aef1c3d4
Revises: ed7eb0525f00
Create Date: 2023-06-12 17:48:48.453718
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '40a8aef1c3d4'
down_revision = 'ed7eb0525f00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'players',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'is_active', sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'password', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name='players_pkey'),
        sa.UniqueConstraint('email', name='players_email_key'),
    )
    op.drop_table('users')
    # ### end Alembic commands ###
