"""remove test field

Revision ID: 423b71fd075d
Revises: 3bc654deaa8b
Create Date: 2023-06-13 14:12:34.136037
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '423b71fd075d'
down_revision = '3bc654deaa8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'new_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customers',
        sa.Column(
            'new_field', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
