"""refact user and customer

Revision ID: 76854ec0af54
Revises: 59112ab9bb07
Create Date: 2023-06-21 22:51:37.390995
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '76854ec0af54'
down_revision = '59112ab9bb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customers', sa.Column('first_name', sa.String(), nullable=False)
    )
    op.add_column(
        'customers', sa.Column('last_name', sa.String(), nullable=False)
    )
    op.drop_column('customers', 'name')
    op.add_column(
        'users', sa.Column('first_name', sa.String(), nullable=False)
    )
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column(
        'customers',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
