"""testing id autoincrement

Revision ID: e6b23cf82495
Revises: 423b71fd075d
Create Date: 2023-06-13 14:30:39.835236
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6b23cf82495'
down_revision = '423b71fd075d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
